replicaCount: 1

nameOverride: novastack-e2e-demo-dev

image:
  repository: ghcr.io/github1001/novastack-e2e-demo
  tag: adbb2a4407f4dcc92f1629e4187ee47684d3c88f
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

config:
  appEnv: dev
